### ISSUE TITLE
Zepto & JQuery Compatibility

### ISSUE THREAD

**Issue by ethanator360** [dgileadi/zepto-page-transitions#13]
Can you run both at the same time?
I have the zepto js and http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js on the same page, and it seems that I can only use one as there's a conflict running both at the same time.

**Comment by dgileadi** [comment]
No.

This plugin may be able to work with JQuery instead of Zepto by replacing
the last (Zepto) in transition.min.js with (JQuery), but I've never tried
it and if it doesn't work you're on your own.

On Mar 10, 2013, at 7:05 PM, ethanator360 notifications@github.com wrote:

Can you run both at the same time?
I have the zepto js and
http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js on the same
page, and it seems that I can only use one as there's a conflict running
both at the same time.

—
Reply to this email directly or view it on
GitHubhttps://github.com/dgileadi/zepto-page-transitions/issues/13
.

**Comment by ethanator360** [comment]
It didn't work, but thanks anyway, David.

**Comment by dbateson** [comment]
it seems to work if you replace the last (Zepto) in transition.min.js with (window.JQuery) not just (JQuery)
