### ISSUE TITLE
Up/Down Transition Slide Issue

### ISSUE THREAD

**Issue by gk-bryn** [dgileadi/zepto-page-transitions#14]
Hi there,  Lovin' this code - just what I was looking for, so thanks for your good work.
I'm having a couple of issues with the slideup and slidedown features - the next page slides in correctly but the current page does not slide out, the way it does when sliding left or right (which looks sweet) Wondered if theres was quick fix for this.?

Also is there a way to add an option to choose between to sliding left or right on each page transition?

Thanks for any help you can give on this one.
B.

**Comment by dgileadi** [comment]
The transitions all come from the .css file.  I honestly haven't tried them all; I got them from another site that was doing something similar.  If you're able to fix the issue and submit a pull request with the fix it would be awesome; otherwise I'll see if I can take a look.  I've been busy recently so it may be a while.

**Comment by dgileadi** [comment]
It turns out that slideup and slidedown are meant to work that way, emulating a modal dialog on iOS for example.  You could copy the slide styles in transition.css/transition.min.css to create your own up/down transition if you like.

As the docs mention you can change the direction of any effect by adding a direction="reverse" or data-direction="reverse" attribute to the link.
