### ISSUE TITLE
页面转换失效

### ISSUE THREAD

**Issue by flyfishtome** [dgileadi/zepto-page-transitions#21]
当第一次切换到新页面时，刷新切换后的页面，会回到上一个页面，并且当前页面不可以切换任何页。
仔细查看了一下，问题可能是 url 造成。 详细请看截图。
![image](https://f.cloud.github.com/assets/2787542/481465/7c76e752-b85e-11e2-926e-e835edc665a2.png)

**Comment by dgileadi** [comment]
English translation courtesy of Google:

> Page conversion failure
> When first switched to a new page, refresh the page after switching will return to the previous page and the current page can not switch any page.
> Closer look at it, the problem may be caused by url. Detailed Look at screenshot.

**Comment by dgileadi** [comment]
A page refresh reloads the original page, ignoring the hash.  The script rewrites the original page's link to #simple2.html, and since that's the hash that's already in the address bar clicking the link doesn't do anything.

One possible fix is to ajax-load any hash item that isn't already on the current page.  Another possible fix is to document that the refresh button isn't well supported :)

**Comment by flyfishtome** [comment]
Thank you for your help,I know where is the problem.I am trying to solve it

**Comment by lroronoazoro** [comment]
Does not support Chinese ? The second page, appear garbled

**Comment by dgileadi** [comment]
This plugin uses ajax to load the new page, and that can have trouble if your encoding isn't UTF-8 (http://stackoverflow.com/questions/553463/jquery-ajax-character-encoding-problem).  Make sure you're using UTF-8 for both your pages.

If that doesn't solve the problem, can you make your pages available somewhere for me to try?

**Comment by hkongm** [comment]
@flyfishtome 我看没啥问题啊？问问详细，修复了哪里？

**Comment by lroronoazoro** [comment]
Thank you very much, I test again

**Comment by dgileadi** [comment]
Closing due to inaction.
